### ISSUE TITLE
Feature Request: Add confetti support

### ISSUE THREAD

**Issue by dongwa** [unovue/inspira-ui#4]
Can you add confetti  component, such as：
https://magicui.design/docs/components/confetti

**Comment by sivareddyuppathi** [comment]
Hi @rahul-vashishtha I'm intrested to work on this new component. Can you assign me if possible. 

If not I'm intrested to contribute even new enhancements.

**Comment by rahul-vashishtha** [comment]
> Hi @rahul-vashishtha I'm intrested to work on this new component. Can you assign me if possible.
> 
> If not I'm intrested to contribute even new enhancements.

Thanks @sivareddyuppathi . I'll assign this to you.

**Comment by WaldemarEnns** [comment]
@rahul-vashishtha @sivareddyuppathi feel free to assign me as an additional reviewer for the PR if you like 🙈

**Comment by rahul-vashishtha** [comment]
> @rahul-vashishtha @sivareddyuppathi feel free to assign me as an additional reviewer for the PR if you like 🙈

Sure. Once PR is ready, I'll assign you as the reviewer

**Comment by rahul-vashishtha** [comment]
Added component in commit 
https://github.com/unovue/inspira-ui/commit/a53df71a187cf822775a59a87870e7e1489d34b4

**Comment by WaldemarEnns** [comment]
@rahul-vashishtha so this is merged and released already?

**Comment by rahul-vashishtha** [comment]
> @rahul-vashishtha so this is merged and released already?

Yes, this component was being requested by multiple users, so I developed it and released it.

**Comment by sivareddyuppathi** [comment]
But I choosen the diffrent path of implimentation and completed of all kinds of confetti buttons and curently implimenting Confetti container, insted of doing the same way how it is in MagicUI adapted to more Vue3 Composables pattern andd added the wraper to confetti library insted of using in directly in components.

Thank you for assigned to me @rahul-vashishtha. and If I implimented any I'll assign to you @WaldemarEnns.

If still you wan to see my way of implimemtation I will rise the PR.

As i'm not aware of urgency I planed to rise the PR by this Sunday.

I'll try next time to complete qucikley if any.

**Comment by rahul-vashishtha** [comment]
> But I choosen the diffrent path of implimentation and completed of all kinds of confetti buttons and curently implimenting Confetti container, insted of doing the same way how it is in MagicUI adapted to more Vue3 Composables pattern andd added the wraper to confetti library insted of using in directly in components.
> 
> Thank you for assigned to me @rahul-vashishtha. and If I implimented any I'll assign to you @WaldemarEnns.
> 
> If still you wan to see my way of implimemtation I will rise the PR.
> 
> As i'm not aware of urgency I planed to rise the PR by this Sunday.
> 
> I'll try next time to complete qucikley if any.
> 
> 

You can add this component also as Confetti alternative. If that seems good, I'll merge it
