### ISSUE TITLE
Performance on the home page very slow

### ISSUE THREAD

**Issue by impressivewebs** [unovue/inspira-ui#41]
Thanks for this component library. Unfortunately, I can't view the home page on my Windows machine because of that giant circle on the home page that basically brings my whole system to a halt. Any chance that can be removed so the performance of the page is better? It's probably not noticeable on more modern systems but it could use some improvement.

**Comment by sivareddyuppathi** [comment]
I think It will make more scense if we come up with some type application log animation. Thoughts @rahul-vashishtha ?

**Comment by rahul-vashishtha** [comment]
@sivareddyuppathi  Can you clarify on that.

**Comment by rahul-vashishtha** [comment]
Removed globe component to improve performance of home page.

https://github.com/rahulv-official/inspira-ui/commit/640cd93991ab59cb6aa4332e305cce393b1b2be5
