### ISSUE TITLE
Docs: Balance Slider page - Preview/code segmented tabs not clickable

### ISSUE THREAD

**Issue by nathangeneral23** [unovue/inspira-ui#58]
**Describe the bug**
The 'Preview' and 'Code' tabs on the [Balance Slider page ](https://inspira-ui.com/components/balance-slider) are not functional. Hovering over the 'header' section—containing the tabs—presents the `grab` cursor, while clicking and dragging moves the slider. It appears that the entire preview component is listening for the drag.

**To Reproduce**

1. Go to [Balance Slider page ](https://inspira-ui.com/components/balance-slider)
2. Click on the 'Preview' and 'Code' tabs at the top of the component preview/example.

**Expected behavior**
The tabs should toggle between the two views.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 130.0.6723.117

**Comment by rahul-vashishtha** [comment]
Fixed in https://github.com/unovue/inspira-ui/commit/8036831eb53c3401726a0d2914a8ac9c3bc5529d
