### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by TheBatman09** [unovue/inspira-ui#68]
**Describe the bug**
Hey me again, I wanted to try the multi step loader and I came across these error in the console:
`Failed to resolve component: UiButton`
`Failed to resolve component: SmartIcon`
I checked and these components are indeed used in the `MultiStepLoader` but I couldn't find theme anywhere in the project, they don't seem to be part of shadcn either, so I can't figure out where it's supposed to come from.

**Comment by rahul-vashishtha** [comment]
Hi @TheBatman09,
UiButton is the part of `shadcn-vue` (depends on how you configure it) and `SmartIcon` is the part of Nuxt project hosting this component.

To resolve this issue, you can replace the `UiButton` and `SmartIcon` with your own `Button` and `Icon`

**Comment by rahul-vashishtha** [comment]
@atif0075 Can we update the component to support the generic TailwindCSS button and simple icons (like unicode) so that it can be used in all types of projects?

**Comment by atif0075** [comment]
Sure

> @atif0075 Can we update the component to support the generic TailwindCSS button and simple icons (like unicode) so that it can be used in all types of projects?

**Comment by TheBatman09** [comment]
Ok, I ended up using nuxt icon thanks for the update guys

**Comment by rahul-vashishtha** [comment]
> Sure
> 
> > @atif0075 Can we update the component to support the generic TailwindCSS button and simple icons (like unicode) so that it can be used in all types of projects?

@atif0075  Please raise a PR once you are done with update.
